### PR TITLE
made image locations global to male motion2d.js re-usable in other plugins

### PR DESCRIPTION
**Pull request by planthaber**
To re-use the motion2d.js script in other plugins, the image locations have to be given globally

### CODE REVIEW

**Comment by doudou** [comment]
Can't you have the relative path as a variable within the page (so that one can override it), and make /ui the default ?

**Comment by planthaber** [comment]
Also thought about that, but that makes the code more unreadable and more importantly devs of additional plugins (meaning pages), have to be aware of the issue and image locations, this way, they can just use the motion2d.js to add controls without caring about paths at all.

Example:

``` html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Asguard Motion2d Control</title>
<!-- external js -->
<script src="/ui/js/external/jquery-2.1.1.js"></script>
<script src="/ui/js/api/WebSock.js"></script>
<script src="/ui/js/api/JSON.js"></script>
<script src="/ui/tasks/js/api/Typelib.js"></script>
<script src="/ui/tasks/js/api/Ports.js"></script>
<script src="/ui/tasks/js/api/Tasks.js"></script>
<script src="/ui/tasks/js/gui/motion2d.js"></script>
<script>
var hostname = "localhost";
function init(){
    var url = "http://localhost:9292/api/tasks/tasks/localhost/simple_controller/ports/motion_command";
    motion2d(url,"m2d");
}
</script>
</head>
<body onload="init()">
<div id="m2d"></div>
</body>
</html>
```

**Comment by doudou** [comment]
> Also thought about that, but that makes the code more unreadable and more importantly devs of additional plugins (meaning pages), have to be aware of the issue and image locations, this way, they can just use the motion2d.js to add controls without caring about paths at all.

If you make /ui the default, you get it working by default but still allow putting the images somewhere else than in the root

**Comment by planthaber** [comment]
Updated the PR, optional parameter to optionally prefix image url with a global path

**Comment by goldhoorn** [comment]
No comments seems to be left

**Pull request merged**
